### PR TITLE
Feature/add author name

### LINKED ISSUE #9: Add the feature of author name in the Card
- Create a feature of author name in the Card for the affirmation.
- The card should show author of the affirmation at the bottom right corner.
- Add appropriate strings to `strings.xml` file for authors corresponding to affirmations.
- Update the model of the Affirmation data class.
- Update the dataSource to include this third parameter.
- Update the code in the `MainActivity.kt` to show author name.

### PR DESCRIPTION
**Pull request by TERRA2k5**
Required changes changes made to fix #9

### CODE REVIEW

**Comment by Abinash6000** [comment]
This is good. Can you attach send some screenshots of the app after running it in emulator or your device?

**Comment by TERRA2k5** [comment]
Sure!!

[Screenshot_2024-10-23-07-22-45-295_com.project.affirmations.jpg](https://github.com/user-attachments/assets/b22102d0-d742-465e-bdf0-0f85ffbe1707)

**Comment by Abinash6000** [comment]
Can you give a screenshot after running it in emulator or your device?

**Comment by Abinash6000** [comment]
Thanks @TERRA2k5 you're very helpful !!!

**Pull request merged**
